### ISSUE TITLE
Agenda items lacking related bill entities cause ocd-event endpoint error

### ISSUE THREAD

**Issue by patcon** [opencivicdata/imago#80]
We were only adding related bills to agenda items when it was a "votable" event, assuming that informational and presentation agenda items didn't have related bills.

```
2016-03-14T05:39:45.732774+00:00 heroku[router]: at=info method=GET path="/ocd-event/f00dbad3-1537-4877-95af-7698492340e4" host=toronto-ocd-api.herokuapp.com request_id=eac1fb43-a602-449d-906a-1910b40c99cf fwd="174.117.101.98" dyno=web.1 connect=0ms service=3ms status=301 bytes=248
2016-03-14T05:39:45.730297+00:00 app[web.1]: WARNING Not Found: /ocd-event/f00dbad3-1537-4877-95af-7698492340e4
2016-03-14T05:39:45.832606+00:00 app[web.1]: ERROR Internal Server Error: /ocd-event/f00dbad3-1537-4877-95af-7698492340e4/
2016-03-14T05:39:45.832617+00:00 app[web.1]: Traceback (most recent call last):
2016-03-14T05:39:45.832618+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
2016-03-14T05:39:45.832622+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2016-03-14T05:39:45.832619+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2016-03-14T05:39:45.832620+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
2016-03-14T05:39:45.832632+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2016-03-14T05:39:45.832632+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
2016-03-14T05:39:45.832634+00:00 app[web.1]:     return bound_func(*args, **kwargs)
2016-03-14T05:39:45.832635+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2016-03-14T05:39:45.832633+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
2016-03-14T05:39:45.832635+00:00 app[web.1]:     return view_func(*args, **kwargs)
2016-03-14T05:39:45.832636+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
2016-03-14T05:39:45.832637+00:00 app[web.1]:     return func.__get__(self, type(self))(*args2, **kwargs2)
2016-03-14T05:39:45.832638+00:00 app[web.1]:     response = super(Endpoint, self).dispatch(request, *args, **kwargs)
2016-03-14T05:39:45.832637+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/views.py", line 106, in dispatch
2016-03-14T05:39:45.832639+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
2016-03-14T05:39:45.832640+00:00 app[web.1]:     return fn(self, request, *args, **kwargs)
2016-03-14T05:39:45.832639+00:00 app[web.1]:     return handler(request, *args, **kwargs)
2016-03-14T05:39:45.832640+00:00 app[web.1]:   File "/app/.heroku/src/imago-master/imago/helpers.py", line 137, in _
2016-03-14T05:39:45.832641+00:00 app[web.1]:     return fn(self, request, *args, **kwargs)
2016-03-14T05:39:45.832641+00:00 app[web.1]:   File "/app/.heroku/src/imago-master/imago/helpers.py", line 122, in _
2016-03-14T05:39:45.832642+00:00 app[web.1]:   File "/app/.heroku/src/imago-master/imago/helpers.py", line 391, in get
2016-03-14T05:39:45.832642+00:00 app[web.1]:     serialized = serialize(obj, **config)
2016-03-14T05:39:45.832643+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 205, in serialize
2016-03-14T05:39:45.832643+00:00 app[web.1]:     exclude=exclude, fixup=fixup)
2016-03-14T05:39:45.832644+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 109, in serialize_model
2016-03-14T05:39:45.832644+00:00 app[web.1]:     data[k] = serialize(getattr(obj, k), **v)
2016-03-14T05:39:45.832645+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 193, in serialize
2016-03-14T05:39:45.832645+00:00 app[web.1]:     return [subs(i) for i in src.all()]
2016-03-14T05:39:45.832645+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 193, in <listcomp>
2016-03-14T05:39:45.832646+00:00 app[web.1]:     return [subs(i) for i in src.all()]
2016-03-14T05:39:45.832646+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 190, in subs
2016-03-14T05:39:45.832647+00:00 app[web.1]:     exclude=exclude, fixup=fixup)
2016-03-14T05:39:45.832647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 205, in serialize
2016-03-14T05:39:45.832648+00:00 app[web.1]:     exclude=exclude, fixup=fixup)
2016-03-14T05:39:45.832648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 109, in serialize_model
2016-03-14T05:39:45.832648+00:00 app[web.1]:     data[k] = serialize(getattr(obj, k), **v)
2016-03-14T05:39:45.832649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 193, in serialize
2016-03-14T05:39:45.832649+00:00 app[web.1]:     return [subs(i) for i in src.all()]
2016-03-14T05:39:45.832650+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 193, in <listcomp>
2016-03-14T05:39:45.832650+00:00 app[web.1]:     return [subs(i) for i in src.all()]
2016-03-14T05:39:45.832650+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 190, in subs
2016-03-14T05:39:45.832651+00:00 app[web.1]:     exclude=exclude, fixup=fixup)
2016-03-14T05:39:45.832651+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 205, in serialize
2016-03-14T05:39:45.832651+00:00 app[web.1]:     exclude=exclude, fixup=fixup)
2016-03-14T05:39:45.832652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/restless/models.py", line 109, in serialize_model
2016-03-14T05:39:45.832652+00:00 app[web.1]:     data[k] = serialize(getattr(obj, k), **v)
2016-03-14T05:39:45.832652+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/opencivicdata/models/event.py", line 121, in entity_name
2016-03-14T05:39:45.832671+00:00 app[web.1]: AttributeError: 'Bill' object has no attribute 'name'
2016-03-14T05:39:45.832667+00:00 app[web.1]:     return self.bill.name
2016-03-14T05:39:45.891105+00:00 heroku[router]: at=info method=GET path="/ocd-event/f00dbad3-1537-4877-95af-7698492340e4/" host=toronto-ocd-api.herokuapp.com request_id=6edf762e-6ce7-4ada-84fd-3245d7e4d6ed fwd="174.117.101.98" dyno=web.1 connect=0ms service=92ms status=500 bytes=210
```

**Comment by patcon** [comment]
Oops. In the honoured tradition of "take-backs" (and given that no one has claimed "no take-backs"), I'm going to retract this :)

Turns out we were using an old commit of python-opencivicdata-django, before bill.name was changed to bill.identifier
https://github.com/opencivicdata/python-opencivicdata-django/blame/master/opencivicdata/models/event.py#L122

Sorry for the noise!
